
import { BabyName, Gender, NameStyle } from './types';

// Helper to assign styles based on name characteristics
const S = NameStyle;

export const INITIAL_NAMES: BabyName[] = [
  { id: '1', hebrew: 'ארי', transliteration: 'Ari', meaning: 'אריה, סמל לגבורה וכוח', gender: Gender.BOY, style: [S.MODERN], isTrending: true },
  { id: '2', hebrew: 'אביגיל', transliteration: 'Abigail', meaning: 'דמות מקראית, שמחת האב', gender: Gender.GIRL, style: [S.CLASSIC, S.INTERNATIONAL] },
  { id: '3', hebrew: 'לביא', transliteration: 'Lavi', meaning: 'אריה, מלך החיות', gender: Gender.BOY, style: [S.MODERN], isTrending: true },
  { id: '4', hebrew: 'מאיה', transliteration: 'Maya', meaning: 'מים בלטינית, וגם שילוב של אמא ויה', gender: Gender.GIRL, style: [S.MODERN, S.INTERNATIONAL], isTrending: true },
  { id: '5', hebrew: 'נועם', transliteration: 'Noam', meaning: 'נעימות, טוב לב', gender: Gender.UNISEX, style: [S.CLASSIC, S.MODERN], isTrending: true },
  { id: '6', hebrew: 'איתן', transliteration: 'Eitan', meaning: 'חזק, יציב', gender: Gender.BOY, style: [S.CLASSIC] },
  { id: '7', hebrew: 'תמר', transliteration: 'Tamar', meaning: 'עץ התמר, משבעת המינים', gender: Gender.GIRL, style: [S.CLASSIC] },
  { id: '8', hebrew: 'עומר', transliteration: 'Omer', meaning: 'שיבולים, שם של תקופה חקלאית', gender: Gender.UNISEX, style: [S.MODERN], isTrending: true },
  { id: '9', hebrew: 'אורי', transliteration: 'Ori', meaning: 'האור שלי', gender: Gender.UNISEX, style: [S.CLASSIC, S.MODERN] },
  { id: '10', hebrew: 'אלמה', transliteration: 'Alma', meaning: 'נשמה או עלמה צעירה', gender: Gender.GIRL, style: [S.MODERN, S.INTERNATIONAL] },
  { id: '11', hebrew: 'דניאל', transliteration: 'Daniel', meaning: "ה' הוא הדיין שלי", gender: Gender.UNISEX, style: [S.CLASSIC, S.INTERNATIONAL] },
  { id: '12', hebrew: 'אדל', transliteration: 'Adele', meaning: 'אצילות (בגרמנית)', gender: Gender.GIRL, style: [S.INTERNATIONAL] },
  { id: '13', hebrew: 'גיא', transliteration: 'Guy', meaning: 'עמק בין הרים', gender: Gender.BOY, style: [S.MODERN] },
  { id: '14', hebrew: 'רוני', transliteration: 'Roni', meaning: 'השמחה שלי', gender: Gender.UNISEX, style: [S.MODERN] },
  { id: '15', hebrew: 'יהונתן', transliteration: 'Yehonatan', meaning: 'מתנת האל', gender: Gender.BOY, style: [S.CLASSIC] },
  { id: '16', hebrew: 'ליבי', transliteration: 'Libi', meaning: 'הלב שלי', gender: Gender.GIRL, style: [S.MODERN], isTrending: true },
  { id: '17', hebrew: 'עמית', transliteration: 'Amit', meaning: 'חבר, רע', gender: Gender.UNISEX, style: [S.MODERN] },
  { id: '18', hebrew: 'איילה', transliteration: 'Ayala', meaning: 'נקבת האייל, סמל לחן', gender: Gender.GIRL, style: [S.CLASSIC, S.MODERN], isTrending: true },
  { id: '19', hebrew: 'יהלי', transliteration: 'Yahli', meaning: "ה' לי, או יאיר לי", gender: Gender.UNISEX, style: [S.MODERN, S.UNIQUE], isTrending: true },
  { id: '20', hebrew: 'אמיר', transliteration: 'Amir', meaning: 'צמרת העץ', gender: Gender.BOY, style: [S.CLASSIC] },
  { id: '21', hebrew: 'שירה', transliteration: 'Shira', meaning: 'שיר, פיוט, זמרה', gender: Gender.GIRL, style: [S.CLASSIC, S.MODERN] },
  { id: '22', hebrew: 'איתי', transliteration: 'Itai', meaning: 'דמות מקראית, נאמנות', gender: Gender.BOY, style: [S.CLASSIC] },
  { id: '23', hebrew: 'רומי', transliteration: 'Romy', meaning: 'רוממות, גובה', gender: Gender.GIRL, style: [S.MODERN, S.INTERNATIONAL], isTrending: true },
  { id: '24', hebrew: 'דוד', transliteration: 'David', meaning: 'אהוב, מלך ישראל', gender: Gender.BOY, style: [S.CLASSIC] },
  { id: '25', hebrew: 'אלה', transliteration: 'Ella', meaning: 'עץ ארץ ישראלי חזק', gender: Gender.GIRL, style: [S.MODERN, S.INTERNATIONAL], isTrending: true },
  { id: '26', hebrew: 'אופיר', transliteration: 'Ofir', meaning: 'ארץ מקראית עשירה בזהב', gender: Gender.UNISEX, style: [S.CLASSIC, S.UNIQUE] },
  { id: '27', hebrew: 'ליה', transliteration: 'Lia', meaning: "לי ה'", gender: Gender.GIRL, style: [S.MODERN, S.INTERNATIONAL], isTrending: true },
  { id: '28', hebrew: 'מעיין', transliteration: 'Maayan', meaning: 'מקור מים זכים', gender: Gender.UNISEX, style: [S.MODERN] },
  { id: '29', hebrew: 'עילאי', transliteration: 'Ilai', meaning: 'עליון, נשגב', gender: Gender.BOY, style: [S.MODERN, S.UNIQUE] },
  { id: '30', hebrew: 'נועה', transliteration: 'Noa', meaning: 'תנועה, דמות מקראית חזקה', gender: Gender.GIRL, style: [S.CLASSIC, S.MODERN], isTrending: true },
  { id: '31', hebrew: 'אדר', transliteration: 'Adar', meaning: 'חודש של שמחה, הדר', gender: Gender.UNISEX, style: [S.UNIQUE] },
  { id: '32', hebrew: 'מיקה', transliteration: 'Mika', meaning: 'מתנת אל, זיו', gender: Gender.GIRL, style: [S.MODERN, S.INTERNATIONAL], isTrending: true },
  { id: '33', hebrew: 'עידו', transliteration: 'Ido', meaning: 'נביא מקראי, עדיי', gender: Gender.BOY, style: [S.CLASSIC] },
  { id: '34', hebrew: 'יובל', transliteration: 'Yuval', meaning: 'נחל, זרם מים', gender: Gender.UNISEX, style: [S.CLASSIC, S.MODERN] },
  { id: '35', hebrew: 'שי', transliteration: 'Shai', meaning: 'מתנה, דורון', gender: Gender.UNISEX, style: [S.MODERN] },
  { id: '36', hebrew: 'ארבל', transliteration: 'Arbel', meaning: 'שם של הר ומושב בגליל', gender: Gender.UNISEX, style: [S.UNIQUE] },
  { id: '37', hebrew: 'זוהר', transliteration: 'Zohar', meaning: 'אור חזק, זיו', gender: Gender.UNISEX, style: [S.CLASSIC] },
  { id: '38', hebrew: 'דרור', transliteration: 'Dror', meaning: 'חופש, ציפור שיר', gender: Gender.UNISEX, style: [S.CLASSIC] },
  { id: '39', hebrew: 'שקד', transliteration: 'Shaked', meaning: 'עץ השקד המקדים לפרוח', gender: Gender.UNISEX, style: [S.MODERN] },
  { id: '40', hebrew: 'רפאל', transliteration: 'Rafael', meaning: 'המלאך המרפא', gender: Gender.BOY, style: [S.CLASSIC, S.INTERNATIONAL] },
  { id: '41', hebrew: 'ליאן', transliteration: 'Lian', meaning: "ה' ענה לי", gender: Gender.GIRL, style: [S.MODERN], isTrending: true },
  { id: '42', hebrew: 'בר', transliteration: 'Bar', meaning: 'בן, תבואה, נקי', gender: Gender.UNISEX, style: [S.MODERN] },
  { id: '43', hebrew: 'נטע', transliteration: 'Neta', meaning: 'צמח צעיר שנשתל', gender: Gender.UNISEX, style: [S.MODERN] },
  { id: '44', hebrew: 'ליאור', transliteration: 'Lior', meaning: 'האור שלי', gender: Gender.UNISEX, style: [S.MODERN] },
  { id: '45', hebrew: 'הלל', transliteration: 'Hallel', meaning: 'שבח והודיה', gender: Gender.UNISEX, style: [S.CLASSIC] },
  { id: '46', hebrew: 'עלמה', transliteration: 'Alma', meaning: 'בחורה צעירה', gender: Gender.GIRL, style: [S.MODERN, S.INTERNATIONAL] },
  { id: '47', hebrew: 'ינאי', transliteration: 'Yanai', meaning: 'מלך חשמונאי, אל יאיר', gender: Gender.BOY, style: [S.CLASSIC, S.UNIQUE] },
  { id: '48', hebrew: 'ריף', transliteration: 'Reef', meaning: 'שונית אלמוגים', gender: Gender.UNISEX, style: [S.UNIQUE, S.INTERNATIONAL], isTrending: true },
  { id: '49', hebrew: 'ירדן', transliteration: 'Yarden', meaning: 'נהר הירדן', gender: Gender.UNISEX, style: [S.CLASSIC] },
  { id: '50', hebrew: 'ארז', transliteration: 'Erez', meaning: 'עץ חזק וגבוה', gender: Gender.BOY, style: [S.CLASSIC] },
  { id: '51', hebrew: 'מיכאל', transliteration: 'Michael', meaning: 'מי כאל, מלאך בשמיים', gender: Gender.BOY },
  { id: '52', hebrew: 'שני', transliteration: 'Shani', meaning: 'צבע אדום עז', gender: Gender.GIRL },
  { id: '53', hebrew: 'גל', transliteration: 'Gal', meaning: 'תנועת המים בים', gender: Gender.UNISEX },
  { id: '54', hebrew: 'נדב', transliteration: 'Nadav', meaning: 'נתן מרצונו, נדיבות', gender: Gender.BOY },
  { id: '55', hebrew: 'יסמין', transliteration: 'Yasmin', meaning: 'פרח ריחני', gender: Gender.GIRL },
  { id: '56', hebrew: 'שחר', transliteration: 'Shahar', meaning: 'אור הבוקר הראשון', gender: Gender.UNISEX },
  { id: '57', hebrew: 'אור', transliteration: 'Or', meaning: 'מקור של הארה', gender: Gender.UNISEX },
  { id: '58', hebrew: 'ליאב', transliteration: 'Liav', meaning: 'לי האב', gender: Gender.BOY },
  { id: '59', hebrew: 'דנה', transliteration: 'Dana', meaning: 'דנה, שופטת', gender: Gender.GIRL },
  { id: '60', hebrew: 'ענבר', transliteration: 'Inbar', meaning: 'שרף מאובן יקר', gender: Gender.GIRL },
  { id: '61', hebrew: 'טל', transliteration: 'Tal', meaning: 'משקעי הלילה', gender: Gender.UNISEX },
  { id: '62', hebrew: 'ניר', transliteration: 'Nir', meaning: 'שדה חרוש', gender: Gender.BOY },
  { id: '63', hebrew: 'ליהיא', transliteration: 'Lihie', meaning: "לי היא ה'", gender: Gender.GIRL },
  { id: '64', hebrew: 'הראל', transliteration: 'Harel', meaning: 'הר האלוהים', gender: Gender.BOY },
  { id: '65', hebrew: 'אביב', transliteration: 'Aviv', meaning: 'עונת הפריחה', gender: Gender.UNISEX },
  { id: '66', hebrew: 'יעלה', transliteration: 'Yaala', meaning: 'נקבת היעל, יופי', gender: Gender.GIRL },
  { id: '67', hebrew: 'רן', transliteration: 'Ran', meaning: 'שר, שמח', gender: Gender.BOY },
  { id: '68', hebrew: 'מור', transliteration: 'Mor', meaning: 'בושם מקראי', gender: Gender.UNISEX },
  { id: '69', hebrew: 'נופר', transliteration: 'Nofar', meaning: 'פרח מים', gender: Gender.GIRL },
  { id: '70', hebrew: 'עדי', transliteration: 'Adi', meaning: 'תכשיט יקר', gender: Gender.UNISEX },
  { id: '71', hebrew: 'אלון', transliteration: 'Alon', meaning: 'עץ אלון חסון', gender: Gender.BOY },
  { id: '72', hebrew: 'מיתר', transliteration: 'Meitar', meaning: 'חוט של כלי נגינה', gender: Gender.UNISEX },
  { id: '73', hebrew: 'קרן', transliteration: 'Keren', meaning: 'קרן אור', gender: Gender.GIRL },
  { id: '74', hebrew: 'לירון', transliteration: 'Liron', meaning: 'לי הרינה והשמחה', gender: Gender.UNISEX },
  { id: '75', hebrew: 'דור', transliteration: 'Dor', meaning: 'דור, תקופה', gender: Gender.UNISEX },
  { id: '76', hebrew: 'עינב', transliteration: 'Einav', meaning: 'פרי הגפן', gender: Gender.GIRL },
  { id: '77', hebrew: 'מעוז', transliteration: 'Maoz', meaning: 'מבצר, הגנה', gender: Gender.BOY },
  { id: '78', hebrew: 'לינוי', transliteration: 'Linoy', meaning: 'לי היופי', gender: Gender.GIRL },
  { id: '79', hebrew: 'ראם', transliteration: 'Reem', meaning: 'חיית פרא מקראית', gender: Gender.BOY },
  { id: '80', hebrew: 'ספיר', transliteration: 'Sapir', meaning: 'אבן חן יקרה', gender: Gender.GIRL },
  { id: '81', hebrew: 'אלעד', transliteration: 'Elad', meaning: 'האל נשאר לעד', gender: Gender.BOY },
  { id: '82', hebrew: 'אורין', transliteration: 'Orin', meaning: 'אור יפה', gender: Gender.GIRL },
  { id: '83', hebrew: 'ים', transliteration: 'Yam', meaning: 'מרחב המים הגדול', gender: Gender.UNISEX },
  { id: '84', hebrew: 'רז', transliteration: 'Raz', meaning: 'סוד, מסתורין', gender: Gender.UNISEX },
  { id: '85', hebrew: 'ניל', transliteration: 'Nil', meaning: 'צבע כחול כהה', gender: Gender.UNISEX },
  { id: '86', hebrew: 'אופק', transliteration: 'Ofek', meaning: 'קו המפגש בין שמים לארץ', gender: Gender.UNISEX },
  { id: '87', hebrew: 'כרמל', transliteration: 'Carmel', meaning: 'כרם אל, שם של הר', gender: Gender.UNISEX },
  { id: '88', hebrew: 'הדס', transliteration: 'Hadas', meaning: 'אחד מארבעת המינים', gender: Gender.GIRL },
  { id: '89', hebrew: 'עילי', transliteration: 'Ilai', meaning: 'עליון, מורם', gender: Gender.BOY },
  { id: '90', hebrew: 'גפן', transliteration: 'Gefen', meaning: 'שיח הענבים', gender: Gender.UNISEX },
  { id: '91', hebrew: 'יערה', transliteration: 'Yaara', meaning: 'חלת דבש, פרח ריחני', gender: Gender.GIRL },
  { id: '92', hebrew: 'יפתח', transliteration: 'Yiftah', meaning: "ה' יפתח, דמות מקראית", gender: Gender.BOY },
  { id: '93', hebrew: 'נלה', transliteration: 'Nala', meaning: 'שם מודרני, אהובה', gender: Gender.GIRL },
  { id: '94', hebrew: 'סתיו', transliteration: 'Stav', meaning: 'עונת המעבר', gender: Gender.UNISEX },
  { id: '95', hebrew: 'נבו', transliteration: 'Nevo', meaning: 'שם של הר מקראי', gender: Gender.BOY },
  { id: '96', hebrew: 'תאיר', transliteration: 'Tair', meaning: 'תפיץ אור', gender: Gender.GIRL },
  { id: '97', hebrew: 'שלו', transliteration: 'Shalev', meaning: 'שקט, רגוע', gender: Gender.UNISEX },
  { id: '98', hebrew: 'יהב', transliteration: 'Yehav', meaning: 'תקווה, ביטחון', gender: Gender.UNISEX },
  { id: '99', hebrew: 'קסם', transliteration: 'Kesem', meaning: 'דבר מופלא', gender: Gender.UNISEX },
  { id: '100', hebrew: 'אוהד', transliteration: 'Ohad', meaning: 'דמות מקראית, אוהב', gender: Gender.BOY },
  { id: '101', hebrew: 'דניאלה', transliteration: 'Daniela', meaning: "ה' הוא הדיין שלי", gender: Gender.GIRL },
  { id: '102', hebrew: 'מיאל', transliteration: 'Miel', meaning: 'מי האל', gender: Gender.GIRL },
  { id: '103', hebrew: 'לביאה', transliteration: 'Levia', meaning: 'אשת האריה', gender: Gender.GIRL },
  { id: '104', hebrew: 'ישי', transliteration: 'Yishai', meaning: 'אבי דוד המלך', gender: Gender.BOY },
  { id: '105', hebrew: 'תהל', transliteration: 'Tahel', meaning: 'תפיץ אור וזוהר', gender: Gender.GIRL },
  { id: '106', hebrew: 'אייל', transliteration: 'Eyal', meaning: 'בעל חיים אצילי', gender: Gender.BOY },
  { id: '107', hebrew: 'תום', transliteration: 'Tom', meaning: 'תמימות, סוף', gender: Gender.UNISEX },
  { id: '108', hebrew: 'ענבל', transliteration: 'Inbal', meaning: 'לשון הפעמון', gender: Gender.GIRL },
  { id: '109', hebrew: 'כפיר', transliteration: 'Kfir', meaning: 'אריה צעיר', gender: Gender.BOY },
  { id: '110', hebrew: 'נויה', transliteration: 'Noya', meaning: "הנוי של ה'", gender: Gender.GIRL },
  { id: '111', hebrew: 'ברק', transliteration: 'Barak', meaning: 'אור בשמים בזמן גשם', gender: Gender.BOY },
  { id: '112', hebrew: 'צליל', transliteration: 'Tzlil', meaning: 'קול מוזיקלי', gender: Gender.GIRL },
  { id: '113', hebrew: 'אלרואי', 'transliteration': 'Elroi', meaning: 'האל רואה אותי', gender: Gender.BOY },
  { id: '114', hebrew: 'מילא', transliteration: 'Mila', meaning: 'מלאה בטוב', gender: Gender.GIRL },
  { id: '115', hebrew: 'יואב', transliteration: 'Yoav', meaning: "ה' הוא אב", gender: Gender.BOY },
  { id: '116', hebrew: 'איילי', transliteration: 'Ayli', meaning: 'האיילה שלי', gender: Gender.GIRL },
  { id: '117', hebrew: 'ניתאי', transliteration: 'Nitai', meaning: 'דמות תנאית', gender: Gender.BOY },
  { id: '118', hebrew: 'אוריאנה', transliteration: 'Oriana', meaning: 'אור יקרות', gender: Gender.GIRL },
  { id: '119', hebrew: 'סהר', transliteration: 'Sahar', meaning: 'הירח במילואו', gender: Gender.UNISEX },
  { id: '120', hebrew: 'גור', transliteration: 'Gur', meaning: 'ולד של חיה', gender: Gender.BOY },
  { id: '121', hebrew: 'סיני', transliteration: 'Sinai', meaning: 'הר סיני', gender: Gender.UNISEX },
  { id: '122', hebrew: 'אוראל', transliteration: 'Orel', meaning: 'האור של האל', gender: Gender.UNISEX },
  { id: '123', hebrew: 'לני', transliteration: 'Leni', meaning: 'שם מודרני', gender: Gender.UNISEX },
  { id: '124', hebrew: 'דגן', transliteration: 'Dagan', meaning: 'תבואת השדה', gender: Gender.BOY },
  { id: '125', hebrew: 'עופרי', transliteration: 'Ofri', meaning: 'העופר שלי', gender: Gender.UNISEX },
  { id: '126', hebrew: 'שלי', transliteration: 'Shely', meaning: 'שייכת לי', gender: Gender.GIRL },
  { id: '127', hebrew: 'נריה', transliteration: 'Neria', meaning: "נר ה'", gender: Gender.UNISEX },
  { id: '128', hebrew: 'בנימין', transliteration: 'Binyamin', meaning: 'בן ימין, דמות מקראית', gender: Gender.BOY },
  { id: '129', hebrew: 'רעות', transliteration: 'Reut', meaning: 'חברות', gender: Gender.GIRL },
  { id: '130', hebrew: 'פלג', transliteration: 'Peleg', meaning: 'נחל קטן', gender: Gender.UNISEX },
  { id: '131', hebrew: 'מורן', transliteration: 'Moran', meaning: 'שם של שיח', gender: Gender.UNISEX },
  { id: '132', hebrew: 'דביר', transliteration: 'Dvir', meaning: 'קודש הקודשים', gender: Gender.BOY },
  { id: '133', hebrew: 'הילה', transliteration: 'Hila', meaning: 'אור סביב הירח', gender: Gender.GIRL },
  { id: '134', hebrew: 'ליאם', transliteration: 'Liam', meaning: 'לי עם', gender: Gender.UNISEX },
  { id: '135', hebrew: 'שרון', transliteration: 'Sharon', meaning: 'אזור בארץ', gender: Gender.UNISEX },
  { id: '136', hebrew: 'אלכס', transliteration: 'Alex', meaning: 'מגן האנושות', gender: Gender.UNISEX },
  { id: '137', hebrew: 'יוגב', transliteration: 'Yogev', meaning: 'עובד אדמה', gender: Gender.BOY },
  { id: '138', hebrew: 'רינת', transliteration: 'Rinat', meaning: 'שירה ושמחה', gender: Gender.GIRL },
  { id: '139', hebrew: 'ליעד', transliteration: 'Liead', meaning: 'לי לעד', gender: Gender.UNISEX },
  { id: '140', hebrew: 'שגיא', transliteration: 'Sagi', meaning: 'גדול, נשגב', gender: Gender.BOY },
  { id: '141', hebrew: 'לימור', transliteration: 'Limor', meaning: 'לי המור (בושם)', gender: Gender.GIRL },
  { id: '142', hebrew: 'שי-לי', transliteration: 'Shai-Li', meaning: 'מתנה לי', gender: Gender.GIRL },
  { id: '143', hebrew: 'עוז', transliteration: 'Oz', meaning: 'כוח, גבורה', gender: Gender.BOY },
  { id: '144', hebrew: 'ארן', transliteration: 'Aran', meaning: 'דמות מקראית, שר', gender: Gender.BOY },
  { id: '145', hebrew: 'צוף', transliteration: 'Tzuf', meaning: 'מיץ הפרחים', gender: Gender.UNISEX },
  { id: '146', hebrew: 'מיטל', transliteration: 'Meital', meaning: 'מי הטל', gender: Gender.GIRL },
  { id: '147', hebrew: 'גלעד', transliteration: 'Gilad', meaning: 'אזור מקראי', gender: Gender.BOY },
  { id: '148', hebrew: 'דלית', transliteration: 'Dalit', meaning: 'ענף של גפן', gender: Gender.GIRL },
  { id: '149', hebrew: 'מרום', transliteration: 'Marom', meaning: 'גובה, שמים', gender: Gender.UNISEX },
  { id: '150', hebrew: 'עידן', transliteration: 'Idan', meaning: 'תקופה בזמן', gender: Gender.BOY },
  { id: '151', hebrew: 'ניצן', transliteration: 'Nitzan', meaning: 'פרח לפני פתיחה', gender: Gender.UNISEX },
  { id: '152', hebrew: 'אושר', transliteration: 'Osher', meaning: 'שמחה פנימית', gender: Gender.UNISEX },
  { id: '153', hebrew: 'עילם', transliteration: 'Eilam', meaning: 'דמות מקראית', gender: Gender.BOY },
  { id: '154', hebrew: 'אורן', transliteration: 'Oren', meaning: 'עץ מחט', gender: Gender.BOY },
  { id: '155', hebrew: 'מיכל', transliteration: 'Michal', meaning: 'בת שאול המלך', gender: Gender.GIRL },
  { id: '156', hebrew: 'רני', transliteration: 'Rani', meaning: 'שירי', gender: Gender.UNISEX },
  { id: '157', hebrew: 'אסף', transliteration: 'Asaf', meaning: 'אסף, קיבץ', gender: Gender.BOY },
  { id: '158', hebrew: 'רוי', transliteration: 'Roy', meaning: 'שם מודרני', gender: Gender.BOY },
  { id: '159', hebrew: 'איילין', transliteration: 'Ayleen', meaning: 'איילה קטנה', gender: Gender.GIRL },
  { id: '160', hebrew: 'עינת', transliteration: 'Einat', meaning: 'מעיין', gender: Gender.GIRL },
  { id: '161', hebrew: 'אלחנן', transliteration: 'Elchanan', meaning: 'האל חנן', gender: Gender.BOY },
  { id: '162', hebrew: 'ליאנה', transliteration: 'Liana', meaning: 'טיפוס, צמח', gender: Gender.GIRL },
  { id: '163', hebrew: 'אדווה', transliteration: 'Adva', meaning: 'גל קטן', gender: Gender.GIRL },
  { id: '164', hebrew: 'סער', transliteration: 'Saar', meaning: 'סופה', gender: Gender.BOY },
  { id: '165', hebrew: 'גיל', transliteration: 'Gil', meaning: 'שמחה, גיל', gender: Gender.UNISEX },
  { id: '166', hebrew: 'שיראל', transliteration: 'Shirel', meaning: 'השיר של האל', gender: Gender.GIRL },
  { id: '167', hebrew: 'שימי', transliteration: 'Shimi', meaning: "שמי ה'", gender: Gender.BOY },
  { id: '168', hebrew: 'יולי', transliteration: 'Yuli', meaning: 'חודש בשנה', gender: Gender.GIRL },
  { id: '169', hebrew: 'יקי', transliteration: 'Yaki', meaning: 'קיצור של יצחק', gender: Gender.BOY },
  { id: '170', hebrew: 'ליז', transliteration: 'Liz', meaning: 'קיצור של אליזבת', gender: Gender.GIRL },
  { id: '171', hebrew: 'נמרוד', transliteration: 'Nimrod', meaning: 'גיבור מקראי', gender: Gender.BOY },
  { id: '172', hebrew: 'נלי', transliteration: 'Nelly', meaning: 'אור', gender: Gender.GIRL },
  { id: '173', hebrew: 'גדי', transliteration: 'Gadi', meaning: 'ולד העיזים', gender: Gender.BOY },
  { id: '174', hebrew: 'שיר', transliteration: 'Shir', meaning: 'פזמון', gender: Gender.GIRL },
  { id: '175', hebrew: 'מירי', transliteration: 'Miri', meaning: 'מרי, מרירות', gender: Gender.GIRL },
  { id: '176', hebrew: 'יוסף', transliteration: 'Yosef', meaning: "ה' יוסיף", gender: Gender.BOY },
  { id: '177', hebrew: 'רונה', transliteration: 'Rona', meaning: 'שמחה', gender: Gender.GIRL },
  { id: '178', hebrew: 'מתן', transliteration: 'Matan', meaning: 'מתנה', gender: Gender.BOY },
  { id: '179', hebrew: 'ליאת', transliteration: 'Liat', meaning: 'לי את', gender: Gender.GIRL },
  { id: '180', hebrew: 'יאיר', transliteration: 'Yair', meaning: 'יביא אור', gender: Gender.BOY },
  { id: '181', hebrew: 'אליאנה', transliteration: 'Eliana', meaning: "ה' ענה לי", gender: Gender.GIRL },
  { id: '182', hebrew: 'אדם', transliteration: 'Adam', meaning: 'האדם הראשון', gender: Gender.BOY },
  { id: '183', hebrew: 'אבנר', transliteration: 'Avner', meaning: 'אבי הנר', gender: Gender.BOY },
  { id: '184', hebrew: 'אנה', transliteration: 'Anna', meaning: 'חן', gender: Gender.GIRL },
  { id: '185', hebrew: 'עזרא', transliteration: 'Ezra', meaning: 'עזרה', gender: Gender.BOY },
  { id: '186', hebrew: 'אורלי', transliteration: 'Orly', meaning: 'האור שלי', gender: Gender.GIRL },
  { id: '187', hebrew: 'בועז', transliteration: 'Boaz', meaning: 'בו עז, כוח', gender: Gender.BOY },
  { id: '188', hebrew: 'שושנה', transliteration: 'Shoshana', meaning: 'פרח הוורד', gender: Gender.GIRL },
  { id: '189', hebrew: 'גרשון', transliteration: 'Gershon', meaning: 'דמות מקראית', gender: Gender.BOY },
  { id: '190', hebrew: 'ענת', transliteration: 'Anat', meaning: 'דמות מקראית', gender: Gender.GIRL },
  { id: '191', hebrew: 'חגי', transliteration: 'Hagai', meaning: "חג ה'", gender: Gender.BOY },
  { id: '192', hebrew: 'יהודית', transliteration: 'Yehudit', meaning: 'דמות מקראית', gender: Gender.GIRL },
  { id: '193', hebrew: 'חנן', transliteration: 'Chanan', meaning: 'חמלה', gender: Gender.BOY },
  { id: '194', hebrew: 'יוכבד', transliteration: 'Yocheved', meaning: "כבוד ה'", gender: Gender.GIRL },
  { id: '195', hebrew: 'מרדכי', transliteration: 'Mordechai', meaning: 'דמות מקראית', gender: Gender.BOY },
  { id: '196', hebrew: 'רחל', transliteration: 'Rachel', meaning: 'כבשה, אם האומה', gender: Gender.GIRL, style: [S.CLASSIC], isTrending: true },
  { id: '197', hebrew: 'שמעון', transliteration: 'Shimon', meaning: "ה' שמע", gender: Gender.BOY, style: [S.CLASSIC] },
  { id: '198', hebrew: 'לאה', transliteration: 'Leah', meaning: 'אם האומה', gender: Gender.GIRL, style: [S.CLASSIC] },
  { id: '199', hebrew: 'פנחס', transliteration: 'Pinchas', meaning: 'דמות מקראית', gender: Gender.BOY, style: [S.CLASSIC, S.UNIQUE] },
  { id: '200', hebrew: 'שרה', transliteration: 'Sarah', meaning: 'שרה, מלכה', gender: Gender.GIRL, style: [S.CLASSIC] },
  { id: '201', hebrew: 'מנחם', transliteration: 'Menachem', meaning: 'מביא נחמה', gender: Gender.BOY, style: [S.CLASSIC] },
  { id: '202', hebrew: 'צפורה', transliteration: 'Tzipora', meaning: 'ציפור', gender: Gender.GIRL, style: [S.CLASSIC, S.UNIQUE] },
  { id: '203', hebrew: 'עקיבא', transliteration: 'Akiva', meaning: 'עקב', gender: Gender.BOY, style: [S.CLASSIC] },
  { id: '204', hebrew: 'רבקה', transliteration: 'Rivka', meaning: 'אם האומה', gender: Gender.GIRL, style: [S.CLASSIC] },
  { id: '205', hebrew: 'עובדיה', transliteration: 'Ovadia', meaning: "עובד ה'", gender: Gender.BOY, style: [S.CLASSIC, S.UNIQUE] },
  { id: '206', hebrew: 'אסתר', transliteration: 'Esther', meaning: 'כוכב, דמות מקראית', gender: Gender.GIRL, style: [S.CLASSIC] },
  { id: '207', hebrew: 'ראובן', transliteration: 'Reuven', meaning: 'ראו בן', gender: Gender.BOY, style: [S.CLASSIC] },
  { id: '208', hebrew: 'מרים', transliteration: 'Miriam', meaning: 'מרי, רוממות', gender: Gender.GIRL, style: [S.CLASSIC] },
  { id: '209', hebrew: 'יצחק', transliteration: 'Yitzhak', meaning: 'צחוק', gender: Gender.BOY, style: [S.CLASSIC] },
  { id: '210', hebrew: 'דבורה', transliteration: 'Dvora', meaning: 'חרק דבש, נביאה', gender: Gender.GIRL, style: [S.CLASSIC] },
  { id: '211', hebrew: 'יעקב', transliteration: 'Yaakov', meaning: 'עקב', gender: Gender.BOY, style: [S.CLASSIC] },
  { id: '212', hebrew: 'רות', transliteration: 'Ruth', meaning: 'רעות', gender: Gender.GIRL, style: [S.CLASSIC] },
  { id: '213', hebrew: 'אברהם', transliteration: 'Avraham', meaning: 'אב המון גויים', gender: Gender.BOY, style: [S.CLASSIC] },
  { id: '214', hebrew: 'חנה', transliteration: 'Chana', meaning: 'חן ותפילה', gender: Gender.GIRL, style: [S.CLASSIC] },
  { id: '215', hebrew: 'אלעזר', transliteration: 'Elazar', meaning: 'האל עזר', gender: Gender.BOY, style: [S.CLASSIC] },
  { id: '216', hebrew: 'נעמי', transliteration: 'Naomi', meaning: 'נעימות', gender: Gender.GIRL, style: [S.CLASSIC, S.INTERNATIONAL] },
  { id: '217', hebrew: 'משה', transliteration: 'Moshe', meaning: 'נמשה מהמים', gender: Gender.BOY, style: [S.CLASSIC] },
  { id: '218', hebrew: 'בתיה', transliteration: 'Batya', meaning: "בת ה'", gender: Gender.GIRL, style: [S.CLASSIC] },
  { id: '219', hebrew: 'אהרון', transliteration: 'Aharon', meaning: 'דמות מקראית', gender: Gender.BOY, style: [S.CLASSIC] },
  { id: '220', hebrew: 'צרויה', transliteration: 'Tzeruya', meaning: 'דמות מקראית', gender: Gender.GIRL, style: [S.CLASSIC, S.UNIQUE] },
  { id: '221', hebrew: 'אפרים', transliteration: 'Efraim', meaning: 'פרייה ורבייה', gender: Gender.BOY },
  { id: '222', hebrew: 'שפרה', transliteration: 'Shifra', meaning: 'יופי ושיפור', gender: Gender.GIRL },
  { id: '223', hebrew: 'נפתלי', transliteration: 'Naftali', meaning: 'נפתולי ה\'', gender: Gender.BOY },
  { id: '224', hebrew: 'פועה', transliteration: 'Puah', meaning: 'דמות מקראית', gender: Gender.GIRL },
  { id: '225', hebrew: 'אביחי', transliteration: 'Avichai', meaning: 'אבי חי', gender: Gender.BOY },
  { id: '226', hebrew: 'ירחמיאל', transliteration: 'Yerachmiel', meaning: 'רחמי האל', gender: Gender.BOY },
  { id: '227', hebrew: 'אמילי', transliteration: 'Emily', meaning: 'עמל (בלטינית)', gender: Gender.GIRL, style: [S.INTERNATIONAL], isTrending: true },
  { id: '228', hebrew: 'טומי', transliteration: 'Tommy', meaning: 'קיצור של תומס/תום', gender: Gender.BOY, style: [S.INTERNATIONAL] },
  { id: '229', hebrew: 'ליב', transliteration: 'Liv', meaning: 'לב', gender: Gender.GIRL, style: [S.MODERN, S.INTERNATIONAL], isTrending: true },
  { id: '230', hebrew: 'מילה', transliteration: 'Mila', meaning: 'מילה, אמירה', gender: Gender.GIRL, style: [S.MODERN, S.INTERNATIONAL], isTrending: true },
  { id: '231', hebrew: 'דילן', transliteration: 'Dylan', meaning: 'בן הים', gender: Gender.BOY, style: [S.INTERNATIONAL] },
  { id: '232', hebrew: 'ליאו', transliteration: 'Leo', meaning: 'אריה', gender: Gender.BOY, style: [S.MODERN, S.INTERNATIONAL], isTrending: true },
  { id: '233', hebrew: 'סול', transliteration: 'Sol', meaning: 'שמש / תו מוזיקלי', gender: Gender.UNISEX, style: [S.UNIQUE, S.INTERNATIONAL] },
  { id: '234', hebrew: 'לואי', transliteration: 'Louie', meaning: 'לוחם מפורסם', gender: Gender.BOY, style: [S.INTERNATIONAL] },
  { id: '235', hebrew: 'נאיה', transliteration: 'Naya', meaning: 'הודיה', gender: Gender.GIRL, style: [S.MODERN, S.UNIQUE], isTrending: true },
  { id: '236', hebrew: 'ריי', transliteration: 'Ray', meaning: 'קרן אור', gender: Gender.UNISEX, style: [S.INTERNATIONAL] },
  { id: '237', hebrew: 'מיילו', transliteration: 'Milo', meaning: 'רחום', gender: Gender.BOY, style: [S.INTERNATIONAL], isTrending: true },
  { id: '238', hebrew: 'אריאה', transliteration: 'Aria', meaning: 'שיר, אוויר', gender: Gender.GIRL, style: [S.MODERN, S.INTERNATIONAL], isTrending: true },
  { id: '239', hebrew: 'אוליבר', transliteration: 'Oliver', meaning: 'עץ זית', gender: Gender.BOY, style: [S.INTERNATIONAL] },
  { id: '240', hebrew: 'אמה', transliteration: 'Emma', meaning: 'שלמה, אוניברסלית', gender: Gender.GIRL, style: [S.INTERNATIONAL], isTrending: true },
  { id: '241', hebrew: 'קים', transliteration: 'Kim', meaning: 'שם מודרני', gender: Gender.GIRL, style: [S.MODERN, S.INTERNATIONAL] },
  { id: '242', hebrew: 'בן', transliteration: 'Ben', meaning: 'בן, ילד', gender: Gender.BOY },
  { id: '243', hebrew: 'רועי', transliteration: 'Roei', meaning: 'הרועה שלי', gender: Gender.BOY },
  { id: '244', hebrew: 'אדיר', transliteration: 'Adir', meaning: 'חזק', gender: Gender.BOY },
  { id: '245', hebrew: 'תומר', transliteration: 'Tomer', meaning: 'עץ תמר', gender: Gender.BOY },
  { id: '246', hebrew: 'יעל', transliteration: 'Yael', meaning: 'חיה', gender: Gender.GIRL },
  { id: '247', hebrew: 'סיון', transliteration: 'Sivan', meaning: 'חודש', gender: Gender.GIRL },
  { id: '248', hebrew: 'נהוראי', transliteration: 'Nehorai', meaning: 'אור', gender: Gender.BOY },
  { id: '249', hebrew: 'ירין', transliteration: 'Yarin', meaning: 'ירון', gender: Gender.UNISEX },
  { id: '250', hebrew: 'טוהר', transliteration: 'Tohar', meaning: 'ניקיון', gender: Gender.UNISEX },
  { id: '251', hebrew: 'דין', transliteration: 'Dean', meaning: 'חוק', gender: Gender.BOY },
  { id: '252', hebrew: 'נהר', transliteration: 'Nahar', meaning: 'מים זורמים', gender: Gender.UNISEX },
  { id: '253', hebrew: 'קשת', transliteration: 'Keshet', meaning: 'קשת בענן', gender: Gender.UNISEX },
  { id: '254', hebrew: 'ניב', transliteration: 'Niv', meaning: 'דיבור', gender: Gender.BOY },
  { id: '255', hebrew: 'יניב', transliteration: 'Yaniv', meaning: 'יביא פרי', gender: Gender.BOY },
  { id: '256', hebrew: 'ירון', transliteration: 'Yaron', meaning: 'ישיר', gender: Gender.BOY },
  { id: '257', hebrew: 'צבי', transliteration: 'Tzvi', meaning: 'חיה', gender: Gender.BOY },
  { id: '258', hebrew: 'זיו', transliteration: 'Ziv', meaning: 'אור', gender: Gender.UNISEX },
  { id: '259', hebrew: 'גבריאל', transliteration: 'Gabriel', meaning: 'גבורת האל', gender: Gender.BOY },
  { id: '260', hebrew: 'אוריאל', transliteration: 'Uriel', meaning: 'אור האל', gender: Gender.BOY },
  { id: '261', hebrew: 'לוי', transliteration: 'Levi', meaning: 'ליווי', gender: Gender.BOY },
  { id: '262', hebrew: 'יהודה', transliteration: 'Yehuda', meaning: 'הודיה', gender: Gender.BOY },
  { id: '263', hebrew: 'ישראל', transliteration: 'Israel', meaning: 'שר עם אל', gender: Gender.BOY },
  { id: '264', hebrew: 'מנשה', transliteration: 'Menashe', meaning: 'נשייה', gender: Gender.BOY },
  { id: '265', hebrew: 'גד', transliteration: 'Gad', meaning: 'מזל', gender: Gender.BOY },
  { id: '266', hebrew: 'אשר', transliteration: 'Asher', meaning: 'אושר', gender: Gender.BOY },
  { id: '267', hebrew: 'דן', transliteration: 'Dan', meaning: 'שפיטה', gender: Gender.BOY },
  { id: '268', hebrew: 'זבולון', transliteration: 'Zevulun', meaning: 'מגורים', gender: Gender.BOY },
  { id: '269', hebrew: 'יששכר', transliteration: 'Yissachar', meaning: 'שכר', gender: Gender.BOY },
  { id: '270', hebrew: 'יהושע', transliteration: 'Yehoshua', meaning: 'ישועה', gender: Gender.BOY },
  { id: '271', hebrew: 'כלב', transliteration: 'Caleb', meaning: 'לב', gender: Gender.BOY },
  { id: '272', hebrew: 'עתניאל', transliteration: 'Otniel', meaning: 'עז האל', gender: Gender.BOY },
  { id: '273', hebrew: 'גדעון', transliteration: 'Gideon', meaning: 'גדיעה', gender: Gender.BOY },
  { id: '274', hebrew: 'שמשון', transliteration: 'Shimshon', meaning: 'שמש', gender: Gender.BOY },
  { id: '275', hebrew: 'שמואל', transliteration: 'Shmuel', meaning: 'שם אל', gender: Gender.BOY },
  { id: '276', hebrew: 'שאול', transliteration: 'Shaul', meaning: 'שאול', gender: Gender.BOY },
  { id: '277', hebrew: 'שלמה', transliteration: 'Shlomo', meaning: 'שלום', gender: Gender.BOY },
  { id: '278', hebrew: 'חזקיהו', transliteration: 'Hezekiah', meaning: 'חוזק האל', gender: Gender.BOY },
  { id: '279', hebrew: 'יאשיהו', transliteration: 'Josiah', meaning: 'ישועת האל', gender: Gender.BOY },
  { id: '280', hebrew: 'נחמיה', transliteration: 'Nehemiah', meaning: "נחמת ה'", gender: Gender.BOY },
  { id: '281', hebrew: 'זכריה', transliteration: 'Zechariah', meaning: "זיכרון ה'", gender: Gender.BOY },
  { id: '282', hebrew: 'מלאכי', transliteration: 'Malachi', meaning: 'מלאך שלי', gender: Gender.BOY },
  { id: '283', hebrew: 'רון', transliteration: 'Ron', meaning: 'שיר', gender: Gender.BOY },
  { id: '284', hebrew: 'מאור', transliteration: 'Maor', meaning: 'מקור אור', gender: Gender.BOY },
  { id: '285', hebrew: 'נתי', transliteration: 'Nati', meaning: 'נתינה', gender: Gender.BOY },
  { id: '286', hebrew: 'דורון', transliteration: 'Doron', meaning: 'מתנה', gender: Gender.BOY },
  { id: '287', hebrew: 'סיגל', transliteration: 'Sigal', meaning: 'פרח', gender: Gender.GIRL },
  { id: '288', hebrew: 'ורד', transliteration: 'Vered', meaning: 'פרח', gender: Gender.GIRL },
  { id: '289', hebrew: 'נרקיס', transliteration: 'Narciss', meaning: 'פרח', gender: Gender.GIRL },
  { id: '290', hebrew: 'לילך', transliteration: 'Lilach', meaning: 'פרח', gender: Gender.GIRL },
  { id: '291', hebrew: 'אורנית', transliteration: 'Ornit', meaning: 'עץ', gender: Gender.GIRL },
  { id: '292', hebrew: 'דקלה', transliteration: 'Dikla', meaning: 'עץ', gender: Gender.GIRL },
  { id: '293', hebrew: 'בשמת', transliteration: 'Basmat', meaning: 'בושם', gender: Gender.GIRL },
  { id: '294', hebrew: 'צאלה', transliteration: 'Tzeela', meaning: 'עץ', gender: Gender.GIRL },
  { id: '295', hebrew: 'אלונה', transliteration: 'Alona', meaning: 'עץ אלון', gender: Gender.GIRL },
  { id: '296', hebrew: 'אילנית', transliteration: 'Ilanit', meaning: 'עץ', gender: Gender.GIRL },
  { id: '297', hebrew: 'הדר', transliteration: 'Hadar', meaning: 'יופי', gender: Gender.GIRL },
  { id: '298', hebrew: 'פאר', transliteration: 'Peer', meaning: 'יופי', gender: Gender.GIRL },
  { id: '299', hebrew: 'זיוה', transliteration: 'Ziva', meaning: 'אור', gender: Gender.GIRL },
  { id: '300', hebrew: 'אורה', transliteration: 'Ora', meaning: 'אור', gender: Gender.GIRL },
  { id: '301', hebrew: 'אורית', transliteration: 'Orit', meaning: 'אור', gender: Gender.GIRL },
  { id: '302', hebrew: 'זהבית', transliteration: 'Zahavit', meaning: 'זהב', gender: Gender.GIRL },
  { id: '303', hebrew: 'פנינה', transliteration: 'Pnina', meaning: 'אבן', gender: Gender.GIRL },
  { id: '304', hebrew: 'מרגלית', transliteration: 'Margalit', meaning: 'אבן', gender: Gender.GIRL },
  { id: '305', hebrew: 'יהלום', transliteration: 'Yahalom', meaning: 'אבן', gender: Gender.GIRL },
  { id: '306', hebrew: 'ברקת', transliteration: 'Bareket', meaning: 'אבן', gender: Gender.GIRL },
  // ... (Previous items up to 306)
// --- תוספות חדשות (מנוקה מכפילויות) ---
{ id: '307', hebrew: 'אריאל', transliteration: 'Ariel', meaning: 'ארי-אל, עוז האל', gender: Gender.UNISEX, style: [S.CLASSIC, S.MODERN], isTrending: true },
{ id: '308', hebrew: 'רותם', transliteration: 'Rotem', meaning: 'שיח מדברי עמיד ויפה', gender: Gender.UNISEX, style: [S.MODERN, S.NATURE], isTrending: true },
{ id: '309', hebrew: 'נגה', transliteration: 'Noga', meaning: 'אור זוהר, כוכב נוגה', gender: Gender.GIRL, style: [S.CLASSIC, S.MODERN], isTrending: true },
{ id: '310', hebrew: 'אגם', transliteration: 'Agam', meaning: 'מקוה מים גדול', gender: Gender.UNISEX, style: [S.MODERN, S.NATURE], isTrending: true },
{ id: '311', hebrew: 'איתמר', transliteration: 'Itamar', meaning: 'אי התמר, דמות מקראית', gender: Gender.BOY, style: [S.CLASSIC, S.MODERN], isTrending: true },
{ id: '312', hebrew: 'יותם', transliteration: 'Yotam', meaning: 'השם תם (שלם)', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '313', hebrew: 'עומרי', transliteration: 'Omri', meaning: 'העומר שלי', gender: Gender.BOY, style: [S.CLASSIC, S.MODERN] },
{ id: '314', hebrew: 'טליה', transliteration: 'Talia', meaning: 'טל-יה', gender: Gender.GIRL, style: [S.CLASSIC, S.MODERN], isTrending: true },
{ id: '315', hebrew: 'עדן', transliteration: 'Eden', meaning: 'גן עדן, עונג', gender: Gender.UNISEX, style: [S.CLASSIC, S.INTERNATIONAL], isTrending: true },
{ id: '316', hebrew: 'כרם', transliteration: 'Kerem', meaning: 'מטע גפנים', gender: Gender.UNISEX, style: [S.MODERN, S.NATURE], isTrending: true },
{ id: '317', hebrew: 'בארי', transliteration: 'Beeri', meaning: 'דמות מקראית (באר שלי)', gender: Gender.BOY, style: [S.CLASSIC, S.MODERN], isTrending: true },
{ id: '318', hebrew: 'עמליה', transliteration: 'Amalia', meaning: 'עמל האל', gender: Gender.GIRL, style: [S.CLASSIC, S.MODERN, S.INTERNATIONAL], isTrending: true },
{ id: '319', hebrew: 'אלומה', transliteration: 'Aluma', meaning: 'אגודת שיבולים', gender: Gender.GIRL, style: [S.CLASSIC, S.NATURE], isTrending: true },
{ id: '320', hebrew: 'ליאל', transliteration: 'Liel', meaning: 'לי האל', gender: Gender.UNISEX, style: [S.MODERN] },
{ id: '321', hebrew: 'מוריה', transliteration: 'Moriah', meaning: 'הר המוריה', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '322', hebrew: 'הודיה', transliteration: 'Hodayah', meaning: 'תודה לאל', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '323', hebrew: 'תהילה', transliteration: 'Tehila', meaning: 'שבח, הערצה', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '324', hebrew: 'נעמה', transliteration: 'Naama', meaning: 'נעימה', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '325', hebrew: 'חן', transliteration: 'Chen', meaning: 'יופי, נעימות', gender: Gender.UNISEX, style: [S.CLASSIC, S.MODERN] },
{ id: '326', hebrew: 'רום', transliteration: 'Rom', meaning: 'גובה, התרוממות', gender: Gender.BOY, style: [S.MODERN] },
{ id: '327', hebrew: 'גלי', transliteration: 'Gali', meaning: 'הגל שלי', gender: Gender.GIRL, style: [S.MODERN] },
{ id: '328', hebrew: 'לוטם', transliteration: 'Lotem', meaning: 'פרח בר ארצישראלי', gender: Gender.UNISEX, style: [S.MODERN, S.NATURE] },
{ id: '329', hebrew: 'ארד', transliteration: 'Arad', meaning: 'עיר בנגב, צבע הברונזה', gender: Gender.BOY, style: [S.MODERN, S.UNIQUE] },
{ id: '330', hebrew: 'קאי', transliteration: 'Kai', meaning: 'ים (בהוואית)', gender: Gender.BOY, style: [S.MODERN, S.INTERNATIONAL], isTrending: true },
{ id: '331', hebrew: 'ריו', transliteration: 'Rio', meaning: 'נהר (בספרדית)', gender: Gender.UNISEX, style: [S.MODERN, S.INTERNATIONAL], isTrending: true },
{ id: '332', hebrew: 'סקיי', transliteration: 'Sky', meaning: 'שמיים (באנגלית)', gender: Gender.UNISEX, style: [S.MODERN, S.INTERNATIONAL], isTrending: true },
{ id: '333', hebrew: 'סאן', transliteration: 'Sun', meaning: 'שמש (באנגלית)', gender: Gender.UNISEX, style: [S.MODERN, S.INTERNATIONAL], isTrending: true },
{ id: '334', hebrew: 'גאיה', transliteration: 'Gaya', meaning: 'אלת האדמה', gender: Gender.GIRL, style: [S.MODERN, S.INTERNATIONAL], isTrending: true },
{ id: '335', hebrew: 'מיכאלה', transliteration: 'Mikaela', meaning: 'מי כאל', gender: Gender.GIRL, style: [S.INTERNATIONAL] },
{ id: '336', hebrew: 'אן', transliteration: 'Ann', meaning: 'חנה (גרסה בינלאומית)', gender: Gender.GIRL, style: [S.MODERN, S.INTERNATIONAL], isTrending: true },
{ id: '337', hebrew: 'לירי', transliteration: 'Liri', meaning: 'שירי, לירית', gender: Gender.GIRL, style: [S.MODERN, S.UNIQUE], isTrending: true },
{ id: '338', hebrew: 'גוני', transliteration: 'Goni', meaning: 'הגוון שלי', gender: Gender.UNISEX, style: [S.MODERN, S.UNIQUE] },
{ id: '339', hebrew: 'אבישג', transliteration: 'Avishag', meaning: 'האב שגא', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '340', hebrew: 'אפרת', transliteration: 'Efrat', meaning: 'שם מקראי', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '341', hebrew: 'מרב', transliteration: 'Merav', meaning: 'בת שאול המלך', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '342', hebrew: 'שלומי', transliteration: 'Shlomi', meaning: 'השלום שלי', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '343', hebrew: 'קובי', transliteration: 'Kobi', meaning: 'קיצור ליעקב', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '344', hebrew: 'ציון', transliteration: 'Zion', meaning: 'ירושלים', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '345', hebrew: 'גולן', transliteration: 'Golan', meaning: 'חבל ארץ בצפון', gender: Gender.BOY, style: [S.CLASSIC, S.NATURE] },
{ id: '346', hebrew: 'סלע', transliteration: 'Sela', meaning: 'אבן גדולה', gender: Gender.BOY, style: [S.MODERN, S.NATURE] },
{ id: '347', hebrew: 'דקל', transliteration: 'Dekel', meaning: 'עץ תמר', gender: Gender.BOY, style: [S.MODERN, S.NATURE] },
{ id: '348', hebrew: 'דולב', transliteration: 'Dolev', meaning: 'עץ נשיר', gender: Gender.BOY, style: [S.MODERN, S.NATURE] },
{ id: '349', hebrew: 'רגב', transliteration: 'Regev', meaning: 'גוש אדמה', gender: Gender.BOY, style: [S.MODERN, S.NATURE] },
{ id: '350', hebrew: 'עמוס', transliteration: 'Amos', meaning: 'נביא מקראי', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '351', hebrew: 'עוזי', transliteration: 'Uzi', meaning: 'הכוח שלי', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '352', hebrew: 'עודד', transliteration: 'Oded', meaning: 'לעודד', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '353', hebrew: 'אהוד', transliteration: 'Ehud', meaning: 'אהוב', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '354', hebrew: 'דנית', transliteration: 'Danit', meaning: 'דינה, דנה', gender: Gender.GIRL, style: [S.MODERN] },
{ id: '355', hebrew: 'גלית', transliteration: 'Galit', meaning: 'גל קטן', gender: Gender.GIRL, style: [S.MODERN] },
{ id: '356', hebrew: 'אירית', transliteration: 'Irit', meaning: 'שם של פרח', gender: Gender.GIRL, style: [S.CLASSIC, S.NATURE] },
{ id: '357', hebrew: 'נורית', transliteration: 'Nurit', meaning: 'פרח האש', gender: Gender.GIRL, style: [S.CLASSIC, S.NATURE] },
{ id: '358', hebrew: 'חגית', transliteration: 'Hagit', meaning: 'נולדה בחג', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '359', hebrew: 'יפעת', transliteration: 'Yifat', meaning: 'יופי, הדר', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '360', hebrew: 'סיגלית', transliteration: 'Sigalit', meaning: 'פרח הסיגל', gender: Gender.GIRL, style: [S.CLASSIC, S.NATURE] },
{ id: '361', hebrew: 'אורנה', transliteration: 'Orna', meaning: 'עץ אורן', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '362', hebrew: 'סמדר', transliteration: 'Smadar', meaning: 'פרח הגפן', gender: Gender.GIRL, style: [S.CLASSIC, S.NATURE] },
{ id: '363', hebrew: 'צופיה', transliteration: 'Tzofia', meaning: 'צופה', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '364', hebrew: 'רווית', transliteration: 'Ravit', meaning: 'רוויה במים', gender: Gender.GIRL, style: [S.MODERN] },
{ id: '365', hebrew: 'אביה', transliteration: 'Avia', meaning: 'אבי הוא האל', gender: Gender.UNISEX, style: [S.CLASSIC] },
{ id: '366', hebrew: 'עתי', transliteration: 'Ati', meaning: 'העתיד שלי', gender: Gender.BOY, style: [S.MODERN, S.UNIQUE] },
{ id: '367', hebrew: 'תימור', transliteration: 'Timor', meaning: 'תמר (עץ) או החלפה', gender: Gender.UNISEX, style: [S.UNIQUE] },
{ id: '368', hebrew: 'ירדנה', transliteration: 'Yardena', meaning: 'נהר הירדן', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '369', hebrew: 'שלומית', transliteration: 'Shlomit', meaning: 'שלום, רגועה', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '370', hebrew: 'מלכה', transliteration: 'Malka', meaning: 'מלכה', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '371', hebrew: 'רינה', transliteration: 'Rina', meaning: 'שמחה', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '372', hebrew: 'דינה', transliteration: 'Dina', meaning: 'דין, משפט', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '373', hebrew: 'זהבה', transliteration: 'Zehava', meaning: 'זהב', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '374', hebrew: 'שולה', transliteration: 'Shula', meaning: 'קיצור לשולמית', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '375', hebrew: 'יפה', transliteration: 'Yaffa', meaning: 'יפה', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '376', hebrew: 'תקווה', transliteration: 'Tikva', meaning: 'תקווה', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '377', hebrew: 'מזל', transliteration: 'Mazal', meaning: 'מזל טוב', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '378', hebrew: 'שמחה', transliteration: 'Simcha', meaning: 'אושר', gender: Gender.UNISEX, style: [S.CLASSIC] },
{ id: '379', hebrew: 'ששון', transliteration: 'Sasson', meaning: 'שמחה', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '380', hebrew: 'חיים', transliteration: 'Haim', meaning: 'חיים', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '381', hebrew: 'נסים', transliteration: 'Nissim', meaning: 'נסים ונפלאות', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '382', hebrew: 'רחמים', transliteration: 'Rahamim', meaning: 'רחמים', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '383', hebrew: 'שלום', transliteration: 'Shalom', meaning: 'שלום', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '384', hebrew: 'מאיר', transliteration: 'Meir', meaning: 'מפיץ אור', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '385', hebrew: 'אריה', transliteration: 'Aryeh', meaning: 'אריה', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '386', hebrew: 'דב', transliteration: 'Dov', meaning: 'דוב', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '387', hebrew: 'זאב', transliteration: 'Zeev', meaning: 'זאב', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '388', hebrew: 'צביקה', transliteration: 'Tzvika', meaning: 'צבי', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '389', hebrew: 'מוטי', transliteration: 'Moti', meaning: 'קיצור למרדכי', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '390', hebrew: 'בני', transliteration: 'Benny', meaning: 'בני, הבן שלי', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '391', hebrew: 'אבי', transliteration: 'Avi', meaning: 'אבא שלי', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '392', hebrew: 'דני', transliteration: 'Danny', meaning: 'דן', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '393', hebrew: 'גילת', transliteration: 'Gilat', meaning: 'שמחה', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '394', hebrew: 'נילי', transliteration: 'Nili', meaning: 'נצח ישראל לא ישקר', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '395', hebrew: 'רותי', transliteration: 'Ruti', meaning: 'חיבה לרות', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '396', hebrew: 'זהורית', transliteration: 'Zehorit', meaning: 'צבע אדום בוהק', gender: Gender.GIRL, style: [S.UNIQUE] },
{ id: '397', hebrew: 'לב', transliteration: 'Lev', meaning: 'לב, רגש', gender: Gender.BOY, style: [S.MODERN, S.INTERNATIONAL], isTrending: true },
{ id: '398', hebrew: 'כרמי', transliteration: 'Carmi', meaning: 'הכרם שלי', gender: Gender.UNISEX, style: [S.CLASSIC, S.NATURE] },
{ id: '399', hebrew: 'משי', transliteration: 'Meshi', meaning: 'בד יקר ורך', gender: Gender.GIRL, style: [S.MODERN] },
{ id: '400', hebrew: 'אפיק', transliteration: 'Afik', meaning: 'מסלול הנחל', gender: Gender.BOY, style: [S.MODERN, S.NATURE] },
{ id: '401', hebrew: 'יער', transliteration: 'Yaar', meaning: 'חורשה גדולה', gender: Gender.UNISEX, style: [S.MODERN, S.NATURE, S.UNIQUE] },
{ id: '402', hebrew: 'כליל', transliteration: 'Klil', meaning: 'מושלם / עץ הכליל', gender: Gender.GIRL, style: [S.UNIQUE, S.NATURE] },
{ id: '403', hebrew: 'סוף', transliteration: 'Suf', meaning: 'צמח מים', gender: Gender.UNISEX, style: [S.MODERN, S.NATURE], isTrending: true },
{ id: '404', hebrew: 'נחשון', transliteration: 'Nachshon', meaning: 'חלוציות', gender: Gender.BOY, style: [S.CLASSIC, S.UNIQUE] },
{ id: '405', hebrew: 'זואי', transliteration: 'Zoe', meaning: 'חיים (ביוונית)', gender: Gender.GIRL, style: [S.MODERN, S.INTERNATIONAL], isTrending: true },
{ id: '406', hebrew: 'ג\'ון', transliteration: 'John', meaning: 'יונתן/יוחנן', gender: Gender.BOY, style: [S.INTERNATIONAL] },
{ id: '407', hebrew: 'אליס', transliteration: 'Alice', meaning: 'אצילה', gender: Gender.GIRL, style: [S.INTERNATIONAL] },
{ id: '408', hebrew: 'שון', transliteration: 'Sean', meaning: 'מתנת האל', gender: Gender.BOY, style: [S.MODERN, S.INTERNATIONAL] },
{ id: '409', hebrew: 'פז', transliteration: 'Paz', meaning: 'זהב', gender: Gender.UNISEX, style: [S.MODERN] },
{ id: '410', hebrew: 'אודם', transliteration: 'Odem', meaning: 'אבן חן אדומה', gender: Gender.GIRL, style: [S.UNIQUE, S.NATURE] },
{ id: '411', hebrew: 'בניה', transliteration: 'Benaya', meaning: 'ה\' בנה', gender: Gender.BOY, style: [S.CLASSIC, S.UNIQUE] },
{ id: '412', hebrew: 'שוהם', transliteration: 'Shoham', meaning: 'אבן חן', gender: Gender.UNISEX, style: [S.UNIQUE, S.NATURE] },
{ id: '413', hebrew: 'זהב', transliteration: 'Zahav', meaning: 'מתכת יקרה', gender: Gender.UNISEX, style: [S.UNIQUE] },
{ id: '414', hebrew: 'עטרה', transliteration: 'Atara', meaning: 'כתר', gender: Gender.GIRL, style: [S.CLASSIC, S.UNIQUE] },
{ id: '415', hebrew: 'מיה', transliteration: 'Mia', meaning: 'מיהו האל / שלי', gender: Gender.GIRL, style: [S.MODERN, S.INTERNATIONAL], isTrending: true },
{ id: '416', hebrew: 'שולמית', transliteration: 'Shulamit', meaning: 'מושלמת', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '417', hebrew: 'אמונה', transliteration: 'Emuna', meaning: 'אמונה, ביטחון', gender: Gender.GIRL, style: [S.CLASSIC, S.UNIQUE] },
{ id: '418', hebrew: 'הללי', transliteration: 'Halleli', meaning: 'הללי את האל', gender: Gender.GIRL, style: [S.MODERN, S.UNIQUE], isTrending: true },
{ id: '419', hebrew: 'יגל', transliteration: 'Yagel', meaning: 'הוא ישמח', gender: Gender.BOY, style: [S.CLASSIC, S.MODERN] },
{ id: '420', hebrew: 'זכאי', transliteration: 'Zakai', meaning: 'טהור, נקי כפיים', gender: Gender.BOY, style: [S.CLASSIC, S.UNIQUE] },
{ id: '421', hebrew: 'עדיאל', transliteration: 'Adiel', meaning: 'תכשיט של האל', gender: Gender.UNISEX, style: [S.MODERN, S.CLASSIC] },
{ id: '422', hebrew: 'רננה', transliteration: 'Renana', meaning: 'שמחה, שירה', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '423', hebrew: 'תבל', transliteration: 'Tevel', meaning: 'העולם, היקום', gender: Gender.UNISEX, style: [S.UNIQUE, S.NATURE] },
{ id: '424', hebrew: 'קמה', transliteration: 'Kama', meaning: 'תבואה בשלה', gender: Gender.GIRL, style: [S.UNIQUE, S.NATURE] },
{ id: '425', hebrew: 'נהרה', transliteration: 'Nehara', meaning: 'אור גדול', gender: Gender.GIRL, style: [S.UNIQUE] },
{ id: '426', hebrew: 'שילת', transliteration: 'Shilat', meaning: 'שיוויטי ה\' לנגדי', gender: Gender.GIRL, style: [S.CLASSIC, S.UNIQUE] },
{ id: '427', hebrew: 'אלישע', transliteration: 'Elisha', meaning: 'האל יושיע', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '428', hebrew: 'עמיחי', transliteration: 'Amichai', meaning: 'העם שלי חי', gender: Gender.BOY, style: [S.CLASSIC, S.MODERN] },
{ id: '429', hebrew: 'ידידיה', transliteration: 'Yedidya', meaning: 'ידיד האל', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '430', hebrew: 'אלנתן', transliteration: 'Elnatan', meaning: 'האל נתן', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '431', hebrew: 'אביאל', transliteration: 'Aviel', meaning: 'אבי הוא האל', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '432', hebrew: 'צור', transliteration: 'Tzur', meaning: 'סלע חזק', gender: Gender.BOY, style: [S.CLASSIC, S.NATURE] },
{ id: '433', hebrew: 'אילון', transliteration: 'Elon', meaning: 'עץ אלון / כוח', gender: Gender.BOY, style: [S.CLASSIC, S.NATURE] },
{ id: '434', hebrew: 'עזריאל', transliteration: 'Azriel', meaning: 'האל הוא עזרי', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '435', hebrew: 'ארנון', transliteration: 'Arnon', meaning: 'נחל שוצף', gender: Gender.BOY, style: [S.CLASSIC, S.NATURE] },
{ id: '436', hebrew: 'שניר', transliteration: 'Snir', meaning: 'החרמון', gender: Gender.BOY, style: [S.MODERN, S.NATURE] },
{ id: '437', hebrew: 'כנרת', transliteration: 'Kineret', meaning: 'ימת הכנרת', gender: Gender.GIRL, style: [S.CLASSIC, S.NATURE] },
{ id: '438', hebrew: 'אשל', transliteration: 'Eshel', meaning: 'עץ האשל', gender: Gender.UNISEX, style: [S.UNIQUE, S.NATURE] },
{ id: '439', hebrew: 'חורש', transliteration: 'Horesh', meaning: 'יער טבעי', gender: Gender.BOY, style: [S.UNIQUE, S.NATURE] },
{ id: '440', hebrew: 'טנא', transliteration: 'Tene', meaning: 'סל ביכורים', gender: Gender.UNISEX, style: [S.UNIQUE, S.NATURE] },
{ id: '441', hebrew: 'לשם', transliteration: 'Leshem', meaning: 'אבן חן', gender: Gender.UNISEX, style: [S.UNIQUE, S.NATURE] },
{ id: '442', hebrew: 'עיבל', transliteration: 'Eival', meaning: 'הר עיבל', gender: Gender.BOY, style: [S.UNIQUE, S.NATURE] },
{ id: '443', hebrew: 'נירן', transliteration: 'Niran', meaning: 'הניר שלהם', gender: Gender.BOY, style: [S.MODERN, S.NATURE] },
{ id: '444', hebrew: 'צוק', transliteration: 'Tzuk', meaning: 'סלע זקוף', gender: Gender.BOY, style: [S.MODERN, S.NATURE] },
{ id: '445', hebrew: 'גילי', transliteration: 'Gili', meaning: 'השמחה שלי', gender: Gender.UNISEX, style: [S.MODERN] },
{ id: '446', hebrew: 'טלי', transliteration: 'Tali', meaning: 'הטל שלי', gender: Gender.GIRL, style: [S.MODERN] },
{ id: '447', hebrew: 'אורחן', transliteration: 'Orchan', meaning: 'אור וחן', gender: Gender.BOY, style: [S.MODERN, S.UNIQUE] },
{ id: '448', hebrew: 'שירן', transliteration: 'Shiran', meaning: 'שיר עליז', gender: Gender.GIRL, style: [S.MODERN] },
{ id: '449', hebrew: 'לי-ים', transliteration: 'Liyam', meaning: 'יש לי ים', gender: Gender.UNISEX, style: [S.MODERN] },
{ id: '450', hebrew: 'מאי', transliteration: 'May', meaning: 'חודש מאי / אביב', gender: Gender.GIRL, style: [S.MODERN, S.INTERNATIONAL] },
{ id: '451', hebrew: 'נווה', transliteration: 'Neve', meaning: 'נאות דשא', gender: Gender.BOY, style: [S.CLASSIC, S.NATURE] },
{ id: '452', hebrew: 'תמיר', transliteration: 'Tamir', meaning: 'גבוה, זקוף', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '453', hebrew: 'עתליה', transliteration: 'Atalya', meaning: 'האל גדול', gender: Gender.GIRL, style: [S.CLASSIC, S.UNIQUE] },
{ id: '454', hebrew: 'אודליה', transliteration: 'Odelia', meaning: 'אודה לאל', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '455', hebrew: 'אוריה', transliteration: 'Oraya', meaning: 'האור של האל', gender: Gender.GIRL, style: [S.MODERN] },
{ id: '456', hebrew: 'חמדה', transliteration: 'Hemda', meaning: 'דבר יקר ואהוב', gender: Gender.GIRL, style: [S.CLASSIC, S.UNIQUE] },
{ id: '457', hebrew: 'בת-אל', transliteration: 'Bat-El', meaning: 'הבת של האל', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '458', hebrew: 'שרית', transliteration: 'Sarit', meaning: 'שרה קטנה', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '459', hebrew: 'עידית', transliteration: 'Idit', meaning: 'אדמה משובחת', gender: Gender.GIRL, style: [S.CLASSIC, S.NATURE] },
{ id: '460', hebrew: 'צופית', transliteration: 'Tzofit', meaning: 'ציפור שיר קטנה', gender: Gender.GIRL, style: [S.MODERN, S.NATURE] },
{ id: '461', hebrew: 'ימית', transliteration: 'Yamit', meaning: 'קשורה לים', gender: Gender.GIRL, style: [S.MODERN, S.NATURE] },
// --- תוספות אקסטרה (שמות שלא היו ברשימות הקודמות) ---
{ id: '462', hebrew: 'נתן', transliteration: 'Natan', meaning: 'האל נתן, נביא מקראי', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '463', hebrew: 'יואל', transliteration: 'Yoel', meaning: 'ה\' הוא האל (נביא)', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '464', hebrew: 'יונה', transliteration: 'Yona', meaning: 'יונה (ציפור / נביא)', gender: Gender.UNISEX, style: [S.CLASSIC, S.NATURE] },
{ id: '465', hebrew: 'הגר', transliteration: 'Hagar', meaning: 'דמות מקראית (אם ישמעאל)', gender: Gender.GIRL, style: [S.CLASSIC] },
{ id: '466', hebrew: 'דפנה', transliteration: 'Dafna', meaning: 'שיח הדפנה (ניצחון)', gender: Gender.GIRL, style: [S.CLASSIC, S.NATURE] },
{ id: '467', hebrew: 'תיאו', transliteration: 'Theo', meaning: 'מתנת האל (בינלאומי)', gender: Gender.BOY, style: [S.MODERN, S.INTERNATIONAL], isTrending: true },
{ id: '468', hebrew: 'לוקה', transliteration: 'Luka', meaning: 'מביא אור (בינלאומי)', gender: Gender.BOY, style: [S.MODERN, S.INTERNATIONAL], isTrending: true },
{ id: '469', hebrew: 'סופי', transliteration: 'Sophie', meaning: 'חכמה (בינלאומי)', gender: Gender.GIRL, style: [S.INTERNATIONAL] },
{ id: '470', hebrew: 'אלי', transliteration: 'Ellie', meaning: 'האור שלי / קיצור לאלינור', gender: Gender.GIRL, style: [S.MODERN, S.INTERNATIONAL], isTrending: true },
{ id: '471', hebrew: 'תכלת', transliteration: 'Tchelet', meaning: 'צבע השמיים, טוהר', gender: Gender.GIRL, style: [S.UNIQUE, S.NATURE] },
{ id: '472', hebrew: 'פלא', transliteration: 'Pele', meaning: 'נס, דבר מופלא', gender: Gender.UNISEX, style: [S.UNIQUE, S.MODERN] },
{ id: '473', hebrew: 'קדם', transliteration: 'Kedem', meaning: 'מזרח / ימי בראשית', gender: Gender.UNISEX, style: [S.UNIQUE, S.MODERN] },
{ id: '474', hebrew: 'עופר', transliteration: 'Ofer', meaning: 'אייל צעיר (עופר)', gender: Gender.BOY, style: [S.CLASSIC, S.NATURE] },
{ id: '475', hebrew: 'רונן', transliteration: 'Ronen', meaning: 'שמח, מרנן', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '476', hebrew: 'ערן', transliteration: 'Eran', meaning: 'עירני, רענן', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '477', hebrew: 'גד', transliteration: 'Gad', meaning: 'מזל (שבט גד)', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '501', hebrew: 'יניב', transliteration: 'Yaniv', meaning: 'יניב (יצמיח) פרי', gender: Gender.BOY, style: [S.MODERN] },
{ id: '502', hebrew: 'ליאור', transliteration: 'Lior', meaning: 'לי-אור (האור שלי)', gender: Gender.UNISEX, style: [S.CLASSIC, S.MODERN] },
{ id: '503', hebrew: 'מתן', transliteration: 'Matan', meaning: 'מתנה', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '504', hebrew: 'נדב', transliteration: 'Nadav', meaning: 'נדיב (בני אהרון)', gender: Gender.BOY, style: [S.CLASSIC] },
{ id: '505', hebrew: 'שחר', transliteration: 'Shahar', meaning: 'אור הבוקר', gender: Gender.UNISEX, style: [S.MODERN, S.NATURE] },
{ id: '506', hebrew: 'ענבר', transliteration: 'Inbar', meaning: 'אבן חן (Amber)', gender: Gender.GIRL, style: [S.CLASSIC, S.NATURE] },
{ id: '507', hebrew: 'נועם', transliteration: 'Noam', meaning: 'נעימות', gender: Gender.UNISEX, style: [S.CLASSIC, S.MODERN] },
{ id: '508', hebrew: 'ניר', transliteration: 'Nir', meaning: 'שדה חרוש', gender: Gender.BOY, style: [S.CLASSIC, S.NATURE] },
{ id: '509', hebrew: 'יעל', transliteration: 'Yael', meaning: 'יעל (חיה אצילית)', gender: Gender.GIRL, style: [S.CLASSIC, S.NATURE] },
{ id: '510', hebrew: 'איתן', transliteration: 'Eitan', meaning: 'חזק, יציב, איתן', gender: Gender.BOY, style: [S.CLASSIC] }
];


export const COLORS = {
  primary: '#80CBC4', // Soft Mint
  secondary: '#546E7A', // Slate Blue Gray
  boy: '#BBDEFB', // Pastel Sky
  girl: '#FFCDD2', // Pastel Pink/Coral
  unisex: '#E1BEE7', // Pastel Purple
  background: '#FFFFFF',
  accent: '#FFF9C4' // Soft Yellow
};
